export interface anxietyDepression {
    a1:string,
    a2:string,
    a3:string,
    a4:string,
    a5:string,
    a6:string,
    a7:string,
    a8:string,
    d1:string,
    d2:string,
    d3:string,
    d4:string,
    d5:string,
    d6:string,
    d7:string,
    d8:string,
    questionare_date:Date
}